### PR TITLE
finish header

### PR DESCRIPTION
**Pull request by nyz83**
**Description:**

I've finished implementing the header section for my portfolio project. This includes:

- Creating the navigation menu
- Making responsive design adjustments

I've added the general requirements of this session.

Header Section Preview

### CODE REVIEW

**Review by Rhaegar121 — CHANGES_REQUESTED** [review]
## STATUS: REQUIRES CHANGES 🚦 ⚠️ ♻️ 

Hi @nyz83 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

close lady

## Highlights 💯 
- No Linter errors ✔️
- Descriptive Pull request summary✔️
- Professional Readme file ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Rhaegar121** [comment]
As you see in the project requirements, you have to design your page exactly like the provided figma design.
`Your website should look exactly like the design (e.g. font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).`

### This is the provided design:
Screenshot (165)


### This is your design:
Screenshot (166)

Please, add the necessary background images to your page according to the figma design.

**Comment by Rhaegar121** [comment]
When you click the hamburger menu, the user cannot see the close btn and the backgrounds are mixing as shown in the screenshot.
Screenshot (167)

I think instead of adding `position: fixed` and `backgound-color: hsl(234, 100%, 69%)` to `.header` class, you can add that properties to just `.header-navigation` class. Because when you have to add another page for your portfolio, you can face error when the whole header element position is fixed. (You wrapped your whole page inside that header element). Best practice is to wrap your navbar and navigation in the header element and wrap other pages in another div or section element.

**Comment by Rhaegar121** [comment]
For responsive design, you need to use `(min-width: 768px)` for desktop screen size. Because this project is a mobile-first design, you need to use specifically (min-width: ...px) property for responsiveness.
```
The website should be responsive, following these breakpoints:
Minimum mobile screen size should be 375px
Minimum desktop screen size should be 768px
```

In your CSS code, you used `@media (max-width: 50em)`. So kindly fix the media query code according to the requirment.

**Comment by nyz83** [comment]
@Rhaegar121, Sir, I accidentally committed an incomplete version with added background icons but still need to work on navigation and media queries.

**Comment by nyz83** [comment]
@Rhaegar121, Sir, I have my navigation changed back to mobile first development, I drop the index.js file because this week deadline is near.

**Review by Rhaegar121 — APPROVED** [review]
## STATUS: APPROVED 🟢

## Hi @nyz83  👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Pull request merged**
